In [1]:
import numpy as np

# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)



print(type(list_))        
print(type(array_list))   

# Q2

for item in list_:
    print(type(item))
for item in array_list:
    print(type(item))

# Q3
array_list = np.array(object=list_, dtype=int)


for item in list_:
    print(type(item))
for item in array_list:
    print(type(item))

# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) shape
print("Shape of num_array:", num_array.shape)

# (ii) size
print("Size of num_array:", num_array.size)

# Q5

zeros_array = np.zeros((3, 3))

print(zeros_array)

# Q6

identity_matrix = np.eye(5)

print(identity_matrix)


<class 'list'>
<class 'numpy.ndarray'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
Shape of num_array: (2, 3)
Size of num_array: 6
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
